//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.ServiceServicios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceServicios.IServiceWCFServicios")]
    public interface IServiceWCFServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFServicios/ObtenerCatalogo", ReplyAction="http://tempuri.org/IServiceWCFServicios/ObtenerCatalogoResponse")]
        System.Data.DataSet ObtenerCatalogo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFServicios/ObtenerCatalogo", ReplyAction="http://tempuri.org/IServiceWCFServicios/ObtenerCatalogoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCatalogoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFServiciosChannel : Presentacion.ServiceServicios.IServiceWCFServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFServiciosClient : System.ServiceModel.ClientBase<Presentacion.ServiceServicios.IServiceWCFServicios>, Presentacion.ServiceServicios.IServiceWCFServicios {
        
        public ServiceWCFServiciosClient() {
        }
        
        public ServiceWCFServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerCatalogo() {
            return base.Channel.ObtenerCatalogo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCatalogoAsync() {
            return base.Channel.ObtenerCatalogoAsync();
        }
    }
}
